# Generated by Django 5.0.6 on 2024-05-15 10:05

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRecipients",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("audience", models.CharField(max_length=1000)),
                ("segment", models.CharField(blank=True, max_length=1000, null=True)),
                ("greeting", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Custom recipients",
            },
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "newsletter_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject for the newsletter. Defaults to page title if blank.",
                        max_length=1000,
                    ),
                ),
                ("newsletter_campaign", models.CharField(blank=True, max_length=1000)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "newsletter_recipients",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtail_newsletter_test.customrecipients",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
