# Generated by Django 5.0.4 on 2024-04-26 14:54

import datetime

import django.db.models.deletion

from django.db import migrations, models

import wagtail_newsletter.test.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Publishing date"
                    ),
                ),
                ("body", wagtail_newsletter.test.fields.StreamField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
