# Generated by Django 5.0.4 on 2024-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterRecipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("audience", models.CharField(max_length=1000)),
                ("segment", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={"verbose_name_plural": "Newsletter recipients"},
        ),
    ]
