# Generated by Django 4.2.11 on 2024-04-29 08:45

import datetime

import django.db.models.deletion

from django.db import migrations, models

import demo.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Publishing date"
                    ),
                ),
                (
                    "body",
                    demo.fields.StreamField(blank=True, use_json_field=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
