# Generated by Django 5.0.4 on 2024-04-29 15:33

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_newsletter", "0001_initial"),
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_campaign",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter.newsletterrecipients",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for the newsletter. Defaults to page title if blank.",
                max_length=1000,
            ),
        ),
    ]
