# Generated by Django 5.0.6 on 2024-05-15 10:08

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRecipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("audience", models.CharField(max_length=1000)),
                ("segment", models.CharField(blank=True, max_length=1000, null=True)),
                ("greeting", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Custom recipients",
            },
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_campaign",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for the newsletter. Defaults to page title if blank.",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="demo.customrecipients",
            ),
        ),
    ]
