# Generated by Django 5.0.6 on 2024-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_alter_articlepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="newsletter_preview",
            field=models.CharField(
                blank=True,
                help_text="The preview that will be displayed in the inbox of the recipient.",
                max_length=1000,
            ),
        ),
    ]
