name: Nightly Wagtail Test

on:
  schedule:
    - cron: '0 1 * * *'
    # At 01:00, daily
  workflow_dispatch:

jobs:
  nightly-wagtail-test:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_EXISTS: ${{ secrets.SLACK_WEBHOOK_URL != '' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: git clone https://github.com/wagtail/wagtail.git

      - run: uv sync --extra=dev
      - run: uv pip install ./wagtail

      - run: uv run pytest -vv

      - name: Report failure
        run: |
          python -m pip install requests
          python ./.github/scripts/report_nightly_build_failure.py
        if: ${{ failure() && env.WEBHOOK_EXISTS == 'true' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
