name: Newsletter CI

on:
  push:
    branches:
      - main
      - 'stable/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv sync --extra=dev
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Run pre-commit
        run: uv tool run --with=pre-commit-uv pre-commit run --all-files
      - uses: jakebailey/pyright-action@v2
        with:
          version: PATH

  test-sqlite:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install
        run: |
          uv sync --extra=ci
      - name: Test
        run: uv run tox
        env:
          DB: sqlite

  test-postgres:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13']

    services:
      postgres:
        image: ${{ matrix.postgres || 'postgres:14' }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install
        run: |
          uv sync --extra=ci
      - name: Test
        run: uv run tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_newsletter
          DB: postgres
